Refactor qemu-kubevirt workflow to better communicate vulnerabilities
Signed-off-by: Byron Marohn <byron.marohn@intel.com>

diff --git a/.github/workflows/qemu-kubevirt.yaml b/.github/workflows/qemu-kubevirt.yaml
--- a/.github/workflows/qemu-kubevirt.yaml
+++ b/.github/workflows/qemu-kubevirt.yaml
@@ -2,7 +2,7 @@
 # SPDX-FileCopyrightText: (C) 2025 Intel Corporation
 # SPDX-License-Identifier: Apache-2.0
 
-name: "QEMU & Kubevirt: Build, Trivy & ClamAV Scan"
+name: "QEMU & Kubevirt"
 run-name: "Workflow (by @${{ github.actor }} via ${{ github.event_name }})"
 
 # Only run at most 1 workflow concurrently per PR, unlimited for branches
@@ -30,12 +30,13 @@ on:
         default: "false"
 
 jobs:
-  qemu-build-and-scan:
+  qemu-build:
     permissions:
       contents: read
     runs-on: ubuntu-24.04
     outputs:
       qemu-artifact-id: ${{ steps.upload-qemu.outputs.artifact-id }}
+      qemu-scan-source-artifact-id: ${{ steps.upload-qemu-scan-source.outputs.artifact-id }}
     steps:
       - name: Harden the runner (Audit all outbound calls)
         uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
@@ -54,6 +55,7 @@ jobs:
         uses: ./.github/actions/setup-tools
         with:
           go: "false"
+          trivy: "false"
 
       - name: Cache QEMU source & build directory
         id: cache-qemu
@@ -66,7 +68,7 @@ jobs:
           path: workspace/qemu-9.1.0
           # Use the hash of the document this workflow is based on to decide whether the build should be re-run or not
           # If the workflow was triggered as a result of pushing a tag, always do a clean cache-free build
-          key: "qemu-binary-${{ github.event_name == 'push' && github.ref_type == 'tag' && github.ref || hashFiles('kubevirt-patch/README.md') }}"
+          key: "qemu-${{ github.event_name == 'push' && github.ref_type == 'tag' && github.ref || hashFiles('kubevirt-patch/README.md') }}"
 
       - name: Build and patch QEMU
         if: ${{ steps.cache-qemu.outputs.cache-hit != 'true' || inputs.disable_cache == 'true' }}
@@ -135,8 +137,50 @@ jobs:
           path: |
             workspace/qemu-9.1.0/build/qemu-system-x86_64
 
+      - name: Upload entire QEMU build directory as a temporary artifact for scanning
+        id: upload-qemu-scan-source
+        # upload-artifact@v4.6.2 released 2025 March 19. SHA pinned for enhanced security
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
+        with:
+          retention-days: 2 # This only needs to be retained long enough for the scanner to run on it
+          name: qemu-scan-source
+          path: |
+            workspace/qemu-9.1.0
+
+  qemu-scan:
+    needs: qemu-build
+    permissions:
+      contents: read
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Checkout Code
+        # checkout@v4.2.2 released 2024 October 23. SHA pinned for enhanced security
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+        with:
+          persist-credentials: false
+          fetch-depth: 0 # All history, not just latest commit
+          ref: ${{ github.event.pull_request.head.sha }} # Check out the actual commit, not a fake merge commit
+
+      - name: Setup Tools & Common Variables
+        uses: ./.github/actions/setup-tools
+        with:
+          go: "false"
+          trivy: "true"
+
+      - name: Download QEMU scan source artifact
+        # download-artifact@v4.3.0 released 2025 April 24. SHA pinned for enhanced security
+        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
+        with:
+          artifact-ids: ${{ needs.qemu-build.outputs.qemu-scan-source-artifact-id }}
+          path: . # Will unpack into a folder with the name used in upload-artifact
+
+      - name: Restore unpacked artifact to correct directory
+        shell: bash
+        run: |
+          mkdir -p workspace
+          mv qemu-scan-source workspace/qemu-9.1.0
+
       - name: trivy qemu source scan
-        continue-on-error: true
         shell: bash
         run: |
           cd workspace/qemu-9.1.0
@@ -145,46 +189,114 @@ jobs:
           trivy image --download-db-only
           curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o trivy-html.tpl
 
-          # Use the downloaded template
-          trivy fs . --format template --template "@trivy-html.tpl" --exit-code 1 --severity MEDIUM,HIGH,CRITICAL -o "trivy_code_scan_qemu.html"
+          # Disable unneccessary warning for OSS project maintainers
+          export TRIVY_DISABLE_VEX_NOTICE=true
 
+          # Scan QEMU code, ignoring some python packages in components that are not copied to the release package
+          # Only scan QEMU for vulnerabilities (disable secrets)
+          trivy fs . \
+            --format json \
+            --scanners vuln \
+            -o trivy_raw_results.json \
+            --skip-files 'docs/requirements.txt' \
+            --skip-files 'roms/u-boot/test/py/requirements.txt'
+
+          # Implementation note: Using || to set the exit code in this way prevents this action component from exiting early when an expected error happens
+          TRIVY_ALL_TYPES_STATUS=0
+          trivy convert \
+            --format template --template "@trivy-html.tpl" \
+            -o "trivy_code_scan_qemu.html" \
+            --exit-code 1 \
+            trivy_raw_results.json || TRIVY_ALL_TYPES_STATUS=$?
+
+          TRIVY_MEDIUM_OR_HIGHER_STATUS=0
+          trivy convert \
+            --format template \
+            --template "@trivy-html.tpl" \
+            -o "trivy_code_scan_qemu_filtered.html" \
+            --exit-code 1 \
+            --severity CRITICAL,HIGH,MEDIUM \
+            trivy_raw_results.json || TRIVY_MEDIUM_OR_HIGHER_STATUS=$?
+
+          # Create a status check using the API to indicate whether vulnerabilities are detected or not
+          # Only fail this specific build step if the scan itself fails - need it to succeed so that artifacts are uploaded
+          if [[ $TRIVY_ALL_TYPES_STATUS -eq 0 ]]; then
+            echo "Trivy scan completed with no vulnerabilities detected"
+            echo "TRIVY_QEMU_STATUS=No vulnerabilities detected" >> $GITHUB_ENV
+            echo "TRIVY_QEMU_STATE=success" >> $GITHUB_ENV
+          elif [[ $TRIVY_ALL_TYPES_STATUS -eq 1 && $TRIVY_MEDIUM_OR_HIGHER_STATUS -eq 0 ]]; then
+            echo "Trivy scan completed with only low-severity vulnerabilities detected"
+            echo "TRIVY_QEMU_STATUS=Trivy detected low-severity vulnerable dependencies. See report artifacts for details." >> $GITHUB_ENV
+            echo "TRIVY_QEMU_STATE=success" >> $GITHUB_ENV
+          elif [[ $TRIVY_ALL_TYPES_STATUS -eq 1 && $TRIVY_MEDIUM_OR_HIGHER_STATUS -eq 1 ]]; then
+            echo "Trivy scan completed with medium-or-higher vulnerabilities detected"
+            echo "TRIVY_QEMU_STATUS=Trivy detected medium, high, or critical vulnerable dependencies. See report artifact for details." >> $GITHUB_ENV
+            echo "TRIVY_QEMU_STATE=failure" >> $GITHUB_ENV
+          else
+            echo "Trivy scan failed."
+            exit $TRIVY_ALL_TYPES_STATUS
+          fi
+
+          # Summarize results on github for quick access
+          echo "# Trivy QEMU Scan Results" >> $GITHUB_STEP_SUMMARY
+          echo "$(trivy convert --format table trivy_raw_results.json)" >> $GITHUB_STEP_SUMMARY
       - name: Upload trivy reports
         # upload-artifact@v4.6.2 released 2025 March 19. SHA pinned for enhanced security
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
         with:
-          name: trivy-code-scan-results-core
+          name: trivy-qemu-results
           path: |
               workspace/qemu-9.1.0/trivy_code_scan_qemu.html
 
       - name: ClamAV QEMU Antivirus Scan
-        continue-on-error: true
         shell: bash
         run: |
           echo "Starting ClamAV scan on workspace/qemu-9.1.0/build/..."
 
+          SCAN_EXIT_CODE=0
           docker run --rm \
             --mount type=bind,source=./workspace/qemu-9.1.0/build/,target=/scandir \
             clamav/clamav:stable \
             clamscan --recursive --log=/scandir/clamav-scan-report.log \
-            /scandir
+            /scandir || SCAN_EXIT_CODE=$?
 
-          SCAN_EXIT_CODE=$?
           sudo chown $USER:$USER workspace/qemu-9.1.0/build/clamav-scan-report.log 2>/dev/null || true
 
           if [ $SCAN_EXIT_CODE -ne 0 ]; then
-            echo "ClamAV scan failed or found issues"
-            exit 1
+            echo "QEMU ClamAV scan failed or found issues"
+            echo "CLAMAV_QEMU_STATUS=Issues detected during antivirus scan" >> $GITHUB_ENV
+            echo "CLAMAV_QEMU_STATE=failure" >> $GITHUB_ENV
+          else
+            echo "QEMU ClamAV scan completed successfully with no issues detected"
+            echo "CLAMAV_QEMU_STATUS=No issues detected" >> $GITHUB_ENV
+            echo "CLAMAV_QEMU_STATE=success" >> $GITHUB_ENV
           fi
+
+          echo "# ClamAV QEMU Scan Results" >> $GITHUB_STEP_SUMMARY
+          echo "$(cat workspace/qemu-9.1.0/build/clamav-scan-report.log | grep -v 'Empty file$')" >> $GITHUB_STEP_SUMMARY
 
       - name: Upload QEMU Antivirus Report
         # upload-artifact@v4.6.2 released 2025 March 19. SHA pinned for enhanced security
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
         with:
-          name: antivirus-qemu
+          name: clamav-qemu-results
           path: workspace/qemu-9.1.0/build/clamav-scan-report.log
 
+      - name: Evaluate Scan Results
+        shell: bash
+        run: |
+          if [[ "$TRIVY_QEMU_STATE" != "success" ]]; then
+            echo "$TRIVY_QEMU_STATUS"
+            exit 1
+          elif [[ "$CLAMAV_QEMU_STATE" != "success" ]]; then
+            echo "$CLAMAV_QEMU_STATUS"
+            exit 1
+          fi
+
+          echo "All scans passed successfully."
+
   kubevirt-build-and-scan:
-    needs: qemu-build-and-scan
+    needs: qemu-build
     permissions:
       contents: read
     runs-on: ubuntu-24.04
@@ -257,7 +369,7 @@ jobs:
         # download-artifact@v4.3.0 released 2025 April 24. SHA pinned for enhanced security
         uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
         with:
-          artifact-ids: ${{ needs.qemu-build-and-scan.outputs.qemu-artifact-id }}
+          artifact-ids: ${{ needs.qemu-build.outputs.qemu-artifact-id }}
           path: . # Will unpack into a folder with the name used in upload-artifact, containing the binary
 
       - name: Build and patch kubevirt
